# Generated by Django 5.1.15 on 2026-04-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='guest_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
