# Generated by Django 5.1.15 on 2026-04-18 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_booking_guest_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='organization',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Tour',
        ),
    ]
