# Generated by Django 5.1.15 on 2026-04-18 09:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('image', models.URLField(max_length=500)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_pct', models.PositiveSmallIntegerField()),
                ('listing_type', models.CharField(choices=[('hotel', 'Hotel'), ('tour', 'Tour'), ('package', 'Package'), ('attraction', 'Attraction'), ('restaurant', 'Restaurant'), ('transfer', 'Transfer')], max_length=20)),
                ('badge', models.CharField(blank=True, choices=[('flash', 'Flash Sale'), ('hot', 'Hot Deal'), ('member', 'Member Price'), ('bestseller', 'Best Seller')], max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='cms.destination')),
            ],
            options={
                'db_table': 'deals',
                'ordering': ['-priority', 'expires_at'],
                'indexes': [models.Index(fields=['is_active', 'expires_at'], name='deals_is_acti_e42703_idx'), models.Index(fields=['priority'], name='deals_priorit_30c352_idx')],
            },
        ),
    ]
