# Generated by Django 5.1.15 on 2026-04-18 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('deals', '0001_initial'),
        ('organizations', '0002_organization_aba_account_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='deal',
            name='object_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals_cms', to='cms.destination'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='discount_pct',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='image',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='deal',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
