# Generated by Django 5.1.15 on 2026-04-15 15:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('org_type', models.CharField(choices=[('HOTEL', 'Hotel'), ('HOMESTAY', 'Homestay'), ('TOUR_OPERATOR', 'Tour Operator'), ('TRANSPORT', 'Transport Company'), ('ATTRACTION', 'Attraction'), ('RESTAURANT', 'Restaurant'), ('TRAVEL_AGENCY', 'Travel Agency')], max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('business_email', models.EmailField(max_length=254)),
                ('business_phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('registration_no', models.CharField(blank=True, max_length=100)),
                ('tax_id', models.CharField(blank=True, max_length=100)),
                ('subscription_tier', models.CharField(choices=[('BASIC', 'Basic'), ('PRO', 'Pro'), ('ENTERPRISE', 'Enterprise')], default='BASIC', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_organizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'organizations',
            },
        ),
        migrations.CreateModel(
            name='OrganizationInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('MANAGER', 'Manager'), ('STAFF', 'Staff'), ('FINANCE', 'Finance')], max_length=20)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='organizations.organization')),
            ],
            options={
                'db_table': 'organization_invitations',
            },
        ),
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('MANAGER', 'Manager'), ('STAFF', 'Staff'), ('FINANCE', 'Finance')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('permission_overrides', models.JSONField(blank=True, default=dict)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_memberships', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'organization_memberships',
            },
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['status'], name='organizatio_status_195db0_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['org_type'], name='organizatio_org_typ_b2fc82_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationinvitation',
            index=models.Index(fields=['token'], name='organizatio_token_779f11_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationinvitation',
            index=models.Index(fields=['email', 'organization'], name='organizatio_email_d21236_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationmembership',
            index=models.Index(fields=['user', 'organization'], name='organizatio_user_id_853deb_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationmembership',
            index=models.Index(fields=['organization', 'role'], name='organizatio_organiz_25ae86_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='organizationmembership',
            unique_together={('user', 'organization')},
        ),
    ]
