# Generated by Django 5.1.15 on 2026-04-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.SlugField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=200)),
                ('tagline', models.CharField(max_length=300)),
                ('image', models.URLField(max_length=500)),
                ('rating_avg', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('listing_count', models.PositiveIntegerField(default=0)),
                ('price_from', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('tag', models.CharField(blank=True, max_length=50)),
                ('categories', models.JSONField(default=list)),
                ('is_trending', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('meta_title', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cms_destinations',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
