# Generated by Django 5.1.15 on 2026-04-18 15:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField()),
                ('name', models.CharField(max_length=100)),
                ('rule_type', models.CharField(choices=[('seasonal_peak', 'Seasonal Peak'), ('seasonal_off', 'Seasonal Off'), ('event_surge', 'Event Surge'), ('promotional', 'Promotional'), ('last_minute', 'Last Minute')], default='seasonal_peak', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('adjustment_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('adjustment_fixed', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('priority', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'inventory_price_rules',
                'ordering': ['-priority', 'start_date'],
            },
        ),
    ]
